package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.ProductOrderRefCancel;
import io.swagger.model.TaskStateType;
import org.threeten.bp.OffsetDateTime;
import org.springframework.validation.annotation.Validated;
import javax.validation.Valid;
import javax.validation.constraints.*;

/**
 * Structure to allow Seller to answer to a cancel order request
 */
@ApiModel(description = "Structure to allow Seller to answer to a cancel order request")
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-09-25T18:12:48.389Z")

public class CancelProductOrder   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("href")
  private String href = null;

  @JsonProperty("state")
  private TaskStateType state = null;

  @JsonProperty("requestedCancellationDate")
  private OffsetDateTime requestedCancellationDate = null;

  @JsonProperty("cancellationReason")
  private String cancellationReason = null;

  @JsonProperty("cancellationDeniedReason")
  private String cancellationDeniedReason = null;

  @JsonProperty("productOrder")
  private ProductOrderRefCancel productOrder = null;

  @JsonProperty("@type")
  private String type = null;

  @JsonProperty("@schemaLocation")
  private String schemaLocation = null;

  public CancelProductOrder id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier for the order cancellation request that is generated by the Seller when the order cancellation is accepted via an API. This is not the order id.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Unique identifier for the order cancellation request that is generated by the Seller when the order cancellation is accepted via an API. This is not the order id.")
  @NotNull


  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CancelProductOrder href(String href) {
    this.href = href;
    return this;
  }

  /**
   * Hyperlink to access order cancellation request.This is not a product order href.
   * @return href
  **/
  @ApiModelProperty(value = "Hyperlink to access order cancellation request.This is not a product order href.")


  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public CancelProductOrder state(TaskStateType state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(required = true, value = "")
  @NotNull

  @Valid

  public TaskStateType getState() {
    return state;
  }

  public void setState(TaskStateType state) {
    this.state = state;
  }

  public CancelProductOrder requestedCancellationDate(OffsetDateTime requestedCancellationDate) {
    this.requestedCancellationDate = requestedCancellationDate;
    return this;
  }

  /**
   * Identifies the date the Seller cancelled the Order.
   * @return requestedCancellationDate
  **/
  @ApiModelProperty(required = true, value = "Identifies the date the Seller cancelled the Order.")
  @NotNull

  @Valid

  public OffsetDateTime getRequestedCancellationDate() {
    return requestedCancellationDate;
  }

  public void setRequestedCancellationDate(OffsetDateTime requestedCancellationDate) {
    this.requestedCancellationDate = requestedCancellationDate;
  }

  public CancelProductOrder cancellationReason(String cancellationReason) {
    this.cancellationReason = cancellationReason;
    return this;
  }

  /**
   * An optional free-form text field for the Seller to provide additional information regarding the reason for the cancellation.
   * @return cancellationReason
  **/
  @ApiModelProperty(value = "An optional free-form text field for the Seller to provide additional information regarding the reason for the cancellation.")


  public String getCancellationReason() {
    return cancellationReason;
  }

  public void setCancellationReason(String cancellationReason) {
    this.cancellationReason = cancellationReason;
  }

  public CancelProductOrder cancellationDeniedReason(String cancellationDeniedReason) {
    this.cancellationDeniedReason = cancellationDeniedReason;
    return this;
  }

  /**
   * If seller denied cancellation request he could here provide reason for this denial
   * @return cancellationDeniedReason
  **/
  @ApiModelProperty(value = "If seller denied cancellation request he could here provide reason for this denial")


  public String getCancellationDeniedReason() {
    return cancellationDeniedReason;
  }

  public void setCancellationDeniedReason(String cancellationDeniedReason) {
    this.cancellationDeniedReason = cancellationDeniedReason;
  }

  public CancelProductOrder productOrder(ProductOrderRefCancel productOrder) {
    this.productOrder = productOrder;
    return this;
  }

  /**
   * Get productOrder
   * @return productOrder
  **/
  @ApiModelProperty(required = true, value = "")
  @NotNull

  @Valid

  public ProductOrderRefCancel getProductOrder() {
    return productOrder;
  }

  public void setProductOrder(ProductOrderRefCancel productOrder) {
    this.productOrder = productOrder;
  }

  public CancelProductOrder type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Technical attribute to extend this class.
   * @return type
  **/
  @ApiModelProperty(value = "Technical attribute to extend this class.")


  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public CancelProductOrder schemaLocation(String schemaLocation) {
    this.schemaLocation = schemaLocation;
    return this;
  }

  /**
   * Technical attribute to extend this class.
   * @return schemaLocation
  **/
  @ApiModelProperty(value = "Technical attribute to extend this class.")


  public String getSchemaLocation() {
    return schemaLocation;
  }

  public void setSchemaLocation(String schemaLocation) {
    this.schemaLocation = schemaLocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CancelProductOrder cancelProductOrder = (CancelProductOrder) o;
    return Objects.equals(this.id, cancelProductOrder.id) &&
        Objects.equals(this.href, cancelProductOrder.href) &&
        Objects.equals(this.state, cancelProductOrder.state) &&
        Objects.equals(this.requestedCancellationDate, cancelProductOrder.requestedCancellationDate) &&
        Objects.equals(this.cancellationReason, cancelProductOrder.cancellationReason) &&
        Objects.equals(this.cancellationDeniedReason, cancelProductOrder.cancellationDeniedReason) &&
        Objects.equals(this.productOrder, cancelProductOrder.productOrder) &&
        Objects.equals(this.type, cancelProductOrder.type) &&
        Objects.equals(this.schemaLocation, cancelProductOrder.schemaLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, href, state, requestedCancellationDate, cancellationReason, cancellationDeniedReason, productOrder, type, schemaLocation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CancelProductOrder {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    requestedCancellationDate: ").append(toIndentedString(requestedCancellationDate)).append("\n");
    sb.append("    cancellationReason: ").append(toIndentedString(cancellationReason)).append("\n");
    sb.append("    cancellationDeniedReason: ").append(toIndentedString(cancellationDeniedReason)).append("\n");
    sb.append("    productOrder: ").append(toIndentedString(productOrder)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    schemaLocation: ").append(toIndentedString(schemaLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

