package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.ProductOrderStateType;
import org.threeten.bp.OffsetDateTime;
import org.springframework.validation.annotation.Validated;
import javax.validation.Valid;
import javax.validation.constraints.*;

/**
 * Structure to define GET without id response. A list of productOrder matching request criteria. Provides Product order summary view.
 */
@ApiModel(description = "Structure to define GET without id response. A list of productOrder matching request criteria. Provides Product order summary view.")
@Validated
public class ProductOrderSummary   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("externalId")
  private String externalId = null;

  @JsonProperty("orderDate")
  private OffsetDateTime orderDate = null;

  @JsonProperty("state")
  private ProductOrderStateType state = null;

  public ProductOrderSummary id(String id) {
    this.id = id;
    return this;
  }

  /**
   * ID created on repository side (OM system) MEF: Unique identifier for the order that is generated by the Seller when the order is initially accepted via an API.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "ID created on repository side (OM system) MEF: Unique identifier for the order that is generated by the Seller when the order is initially accepted via an API.")
  @NotNull


  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ProductOrderSummary externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

  /**
   * ID given by the consumer and only understandable by him (to facilitate his searches afterwards). MEF: Buyer Purchase Order Number
   * @return externalId
  **/
  @ApiModelProperty(required = true, value = "ID given by the consumer and only understandable by him (to facilitate his searches afterwards). MEF: Buyer Purchase Order Number")
  @NotNull


  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public ProductOrderSummary orderDate(OffsetDateTime orderDate) {
    this.orderDate = orderDate;
    return this;
  }

  /**
   * Date when the order was created
   * @return orderDate
  **/
  @ApiModelProperty(required = true, value = "Date when the order was created")
  @NotNull

  @Valid

  public OffsetDateTime getOrderDate() {
    return orderDate;
  }

  public void setOrderDate(OffsetDateTime orderDate) {
    this.orderDate = orderDate;
  }

  public ProductOrderSummary state(ProductOrderStateType state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(required = true, value = "")
  @NotNull

  @Valid

  public ProductOrderStateType getState() {
    return state;
  }

  public void setState(ProductOrderStateType state) {
    this.state = state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductOrderSummary productOrderSummary = (ProductOrderSummary) o;
    return Objects.equals(this.id, productOrderSummary.id) &&
        Objects.equals(this.externalId, productOrderSummary.externalId) &&
        Objects.equals(this.orderDate, productOrderSummary.orderDate) &&
        Objects.equals(this.state, productOrderSummary.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, externalId, orderDate, state);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductOrderSummary {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

